/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as ApiBookingRouteImport } from './routes/api.booking'
import { Route as ApiChatLeadRouteImport } from './routes/api.chat-lead'
import { Route as ApiCreateLeadRouteImport } from './routes/api.create-lead'
import { Route as ApiCreateOrderRouteImport } from './routes/api.create-order'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api.verify-payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingRoute = ApiBookingRouteImport.update({
  id: '/api/booking',
  path: '/api/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatLeadRoute = ApiChatLeadRouteImport.update({
  id: '/api/chat-lead',
  path: '/api/chat-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateLeadRoute = ApiCreateLeadRouteImport.update({
  id: '/api/create-lead',
  path: '/api/create-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/api/booking': typeof ApiBookingRoute
  '/api/chat-lead': typeof ApiChatLeadRoute
  '/api/create-lead': typeof ApiCreateLeadRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/api/booking': typeof ApiBookingRoute
  '/api/chat-lead': typeof ApiChatLeadRoute
  '/api/create-lead': typeof ApiCreateLeadRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/api/booking': typeof ApiBookingRoute
  '/api/chat-lead': typeof ApiChatLeadRoute
  '/api/create-lead': typeof ApiCreateLeadRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-confirmation'
    | '/api/booking'
    | '/api/chat-lead'
    | '/api/create-lead'
    | '/api/create-order'
    | '/api/verify-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-confirmation'
    | '/api/booking'
    | '/api/chat-lead'
    | '/api/create-lead'
    | '/api/create-order'
    | '/api/verify-payment'
  id:
    | '__root__'
    | '/'
    | '/booking-confirmation'
    | '/api/booking'
    | '/api/chat-lead'
    | '/api/create-lead'
    | '/api/create-order'
    | '/api/verify-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  ApiBookingRoute: typeof ApiBookingRoute
  ApiChatLeadRoute: typeof ApiChatLeadRoute
  ApiCreateLeadRoute: typeof ApiCreateLeadRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking': {
      id: '/api/booking'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-lead': {
      id: '/api/chat-lead'
      path: '/api/chat-lead'
      fullPath: '/api/chat-lead'
      preLoaderRoute: typeof ApiChatLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-lead': {
      id: '/api/create-lead'
      path: '/api/create-lead'
      fullPath: '/api/create-lead'
      preLoaderRoute: typeof ApiCreateLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  ApiBookingRoute: ApiBookingRoute,
  ApiChatLeadRoute: ApiChatLeadRoute,
  ApiCreateLeadRoute: ApiCreateLeadRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
